### ISSUE TITLE
Repo güncellemeleri

### ISSUE THREAD

**Issue by s-kali** [beyza-ozben/case#2]
Merhaba,

Projenizi inceledim ve çok beğendim ancak birkaç noktada düzeltme önerebilirim.

- README dosyanızda yazdığınız talimatlar net olmasına karşın kullanıcıların süreci daha iyi anlamasına ve daha hızlı adapte olmasına yardımcı olabilecek kod bloklarını kullanabilirsiniz.
  - Zararlı Bağlantılar API'sinden elde edilen bağlantıların etiketlenmesi için kullanılan scriptin tam olarak nasıl çalıştırıldığını terminal komutu olarak yazmanız örnek olabilir.
- Repoda `about` kısmı boş görünüyor, buraya eklenecek bilgiler reponuzu ziyaret etmeden önce ve sonrasında hakkındaki ilk veriler konusunda diğer kullanıcıları bilgilendirebilir.
- Kaynak olarak belirttiğiniz URL'lerin bir markdown url formatına uygun şekilde yazarak kullanıcıyı yönlendirebilecek bağlantı köprüleri oluşturabilirsiniz.

**Comment by beyza-ozben** [comment]
Merhaba,

Dönüş ve inceleme için teşekkür ederim.

İlgili düzenleme ve eklemelerle README.md belgesini tamamladım.
